export const  constantRouter=[

        {
            path:"/login",
            component:() => import("@/views/login/index.vue"),
            name:"Login",
            meta:{
                title:'登录',
                hidden:true,
                icon:"HomeFilled"
            }
        },
        {
            path:"/",
            component:()=>import("@/layout/index.vue"),
            name:"home",
            meta:{
                title:'首页',
                hidden:false,
                icon:"HomeFilled"
            },
            redirect: '/home',
            children:[
                {
                    path:"/home",
                    component:()=>import("@/views/home/index.vue"),
                    meta:{
                        title:'首页',
                        hidden:false,
                        icon:"HomeFilled"
                    }
                }
            ]
        },
        {
            path:"/screen",
            component:()=>import("@/views/screen/index.vue"),
            name:"Screen",
            meta:{
                title:'数据大屏',
                icon:"Monitor"
            }
        },
        {
            path:"/acl",
            component:()=>import("@/layout/index.vue"),
            name:"Acl",
            meta:{
                title:'权限管理',
                icon:"Lock"
            },
            children:[
                {
                    path:"/acl/user",
                    name:'User',
                    component:()=>import("@/views/acl/user/index.vue"),
                    meta:{
                        title:'用户管理',
                        hidden:false,
                        icon:"User"
                    }
                },
                {
                    path:"/acl/role",
                    component:()=>import("@/views/acl/role/index.vue"),
                    name:'Role',
                    meta:{
                        title:'角色管理',
                        hidden:false,
                        icon:"UserFilled"
                    }
                },
                {
                    path:"/acl/permission",
                    name:'Permission',
                    component:()=>import("@/views/acl/permission/index.vue"),
                    meta:{
                        title:'菜单管理',
                        hidden:false,
                        icon:"Memo"
                    },
                }
            ]
        },
        {
            path:"/product",
            component:()=>import("@/layout/index.vue"),
            name:"Product",
            meta:{
                title:'商品管理',
                icon:"Goods"
            },
            children:[
                {
                    path:'/product/trademark',
                    component:()=>import("@/views/product/trademark/index.vue"),
                    name:'Trademark',
                    meta:{
                        title:'品牌管理',
                        icon:'ShoppingCartFull'
                    }
                },
                {
                    path:'/product/attr',
                    component:()=>import("@/views/product/attr/index.vue"),
                    name:'Attr',
                    meta:{
                        title:'属性管理',
                        icon:'ShoppingCartFull'
                    }
                },
                {
                    path:'/product/spu',
                    component:()=>import("@/views/product/spu/index.vue"),
                    name:'Spu',
                    meta:{
                        title:'SPU管理',
                        icon:'ShoppingCartFull'
                    }
                },
                {
                    path:'/product/sku',
                    component:()=>import("@/views/product/sku/index.vue"),
                    name:'Sku',
                    meta:{
                        title:'SKU管理',
                        icon:'ShoppingCartFull'
                    }
                }
            ]
        },
        {
            path:"/404",
            component:()=>import("@/views/404/index.vue"),
            name:"404",
            meta:{
                title:'404',
                hidden:true,
                icon:"HomeFilled"
            }
        },
        {
            path:"/:pathMatch(.*)*",
            redirect:"/404",
            name:"Any",
            meta:{
                title:'Any',
                hidden:true,
                icon:"HomeFilled"
            }
        }
]